package com.dicoding.manadosnacking;

import java.util.ArrayList;

public class KulinerData {
    public static String [][] data = new String[][]{
            {"Pisang Goroho","Nama pisang goroho memang tidak setenar pisang Ambon ataupun pisang raja, namun buah yang tumbuh di daratan Sulawesi Utara ini memiliki rasa yang tak kalah lezat. Bahkan menurut sejumlah penelitian, pisang goroho memiliki indeks glikemiks yang rendah sehingga cocok dikonsumsi bagi penderita diabetes. Jadi, tak heran jika buah satu ini banyak diburu wisatawan yang datang berkunjung ke Manado.Umumnya, pisang ini akan digoreng tipis-tipis. Kemudian, pisang akan dimakan bersama dengan sambal roa. Cukup unik, bukan? Untuk mencicipi dan membelinya, kamu bisa mampir ke berbagai restoran atau sentra oleh-oleh Manado.","https://blog.traveloka.com/source/uploads/2018/08/31150047_390538651463036_3469708429793165312_n.jpg"},
            {"Pala Manis","Di Manado, buah pala biasa diolah masyarakat setempat bersama cairan gula sehingga menjadi manisan yang legit. Berbeda dari manisan pada umumnya yang terbuat dari buah-buahan segar, di sini kamu justru akan menjumpai banyak pedagang yang menjajakan pala manis. Tak susah untuk menemukan penganan ini karna kamu bisa membelinya di berbagai pusat oleh-oleh khas Manado. Kamu cukup menyiapkan uang sekitar dengan Rp40.000 untuk membeli sebungkus pala manis. Satu hal yang tak kalah menarik, makanan khas ini juga rutin di ekspor hingga Malaysia lho!","https://blog.traveloka.com/source/uploads/2018/08/25021972_1021610581313381_729702294911713280_n.jpg"},
            {"Sambal Ikan Roa","Berada di wilayah pesisir, Kota Manado memiliki hasil laut yang cukup melimpah. Tak heran, jika ada banyak jenis olahan ikan yang bisa kamu temukan di sini. Salah satunya adalah sambal ikan roa, yang juga menjadi oleh-oleh Manado terlaris sampai saat ini. Berbeda dari sambal pada umumnya, sambal khas Manado ini menggunakan ikan roa yang sudah melalui pengasapan sebagai bahan baku utama.Sambal ikan roa bisa awet hingga enam bulan jika disimpan pada suhu ruangan normal dan dapat mencapai satu tahun bila disimpan di kulkas. Jadi, kamu tak perlu khawatir saat harus melalui perjalanan jauh ketika membeli penganan ini sebagai oleh-oleh. Jika tertarik membelinya, kamu hanya perlu menyiapkan uang sekitar Rp35.000 – Rp50.000.","https://blog.traveloka.com/source/uploads/2018/08/33028106_956625671128917_9164610729557360640_n.jpg"},
            {"Cakalang Fufu","Seperti namanya, cakalang fufu merupakan makanan khas Manado yang terbuat dari ikan cakalang yang diberi bumbu, diasap, kemudian dijepit dengan kerangka bambu. Olahan ikan ini menjadi hidangan khas khususnya di daerah Minahasa, Sulawesi Utara. Meski berupa masakan basah,  cakalang fufu tetap bisa menjadi pilihan oleh-oleh khas Manado yang awet.Jika kamu ingin membelinya sebagai buah tangan, mintalah sang penjual untuk mengemasnya dengan rapi dan aman.  Nantinya, kamu perlu memanaskan kembali sebelum dikonsumsi. Cukup panaskan cakalang fufu dengan minyak panas beberapa saat, kamu sudah bisa menikmatinya bersama nasi dan sambal. Dijamin kamu akan ketagihan!","https://blog.traveloka.com/source/uploads/2018/08/11272962_352344861624294_817742143_n.jpg"},
            {"Halua Kenari","Masih terasa asing dengan nama penganan ini? Halua kenari adalah oleh-oleh Manado yang berbentuk seperti gula-gula kacang. Rasa yang dihasilkan manis dan gurih. Uniknya,  kamu bisa merasakan aroma kenari yang begitu khas dan harum sehingga semakin menggugah selera makan.Cita rasa manis penganan ini umumnya dihasilkan dari paduan gula merah yang dicampur dengan kenari. Soal harga tak jadi masalah, kamu cukup menyiapkan bujet Rp60.000 untuk mendapatkan halua kenari dalam kemasan 500 gram. Selain dijadikan oleh-oleh untuk keluarga di rumah, camilan ini juga bisa kamu nikmati selama berkeliling Manado.","https://www.indonesiakaya.com/uploads/_images_gallery/2__IMG_0785_Halua_kenari_dibuat_menggunakan_bahan_utama_kacang_kenari_yang_tumbuh_subur_di_Sulawesi_Utara.jpg"},
            {"Panada","Jika dilihat sepintas, makanan satu ini memiliki bentuk serupa dengan kue pastel. Namun, panada memiliki bahan dan cita rasa yang berbeda. Jika pastel umumnya berisi campuran bihun dan irisan ayam, panada justru diberi isian berupa pepaya muda yang dicampur dengan ikan cakalang bercita rasa pedas.Konon, panada merupakan penganan khas keluarga besar Mandey asal Minahasa. Namun, kini panada sudah dijual bebas di berbagai pusat oleh-oleh. Satu biji panada biasa dijual dengan harga Rp3.000 saja. Sangat terjangkau, bukan?","https://blog.traveloka.com/source/uploads/2018/08/29718359_1669440379812891_709160411227750400_n.jpg"},
            {"Kacang Goyang","Oleh-oleh khas Manado yang bisa kamu bawa pulang selanjutnya adalah kacang goyang. Memiliki bentuk, tekstur, dan warna yang beragam, menjadikan camilan ini menarik dan banyak diburu oleh wisatawan. Konon, nama penganan ini diambil dari teknik pembuatannya yang digoyangkan setelah melalui proses sangrai.Jika ingin membeli kacang goyang sebagai oleh-oleh, kamu hanya perlu menyiapkan uang sekitar Rp10.000 – Rp25.000 untuk mendapatkan satu kemasannya. Tenang saja, kacang goyang ini bisa awet hingga satu bulan, lho! Jadi, bisa sekaligus kamu jadikan stok camilan.","https://blog.traveloka.com/source/uploads/2018/08/22637058_148874392515205_6443535784019492864_n.jpg"},
            {"Dodol Amurang","Tak hanya di Pulau Jawa, dodol juga menjadi salah satu oleh-oleh khas Manado yang sayang untuk dilewatkan. Dinamakan dodol Amurang sebab jajanan legit ini berasal dari kawasan Amurang di Minahasa Selatan. Beberapa penduduk setempat juga menyebutnya dengan nama Dodol Kenari.Dodol Amurang tergolong jajanan tradisional, sebab dibuat menggunakan bahan-bahan alami. Prosesnya, gula aren dan beras ketan akan dihaluskan kemudian dicampur dengan minyak kelapa yang murni. Sajian ini biasa ditemukan ketika ada acara tradisi syukuran warga Minahasa. Namun jika tertarik membawa pulang dodol Amurang, kamu bisa membelinya di pusat oleh-oleh yang banyak dijumpai di pusat Kota Manado.","https://cdn.idntimes.com/content-images/community/2018/08/cb72afcfdeea732e5860d8a81344c3a8.jpg"},
            {"Kue Lampu-Lampu","Pada mulanya, kue lampu-lampu hanya disajikan masyarakat Manado sebagai menu takjil di bulan puasa. Pasalnya, kue ini dipercaya dapat menguatkan daya tahan tubuh selama berpuasa. Selain itu, kue ini cocok dimakan bersama kolak kacang hijau.Penganan ini umumnya terbuat dari tepung terigu, tepung beras, santan, dan gula merah yang dikukus. Proses pembuatan itulah yang akhirnya menghasilkan cita rasa khas dan berbeda dari kebanyakan kue basah kota lainnya.","https://blog.traveloka.com/source/uploads/2018/08/14145354_1075231959233418_1004609004_n.jpg"},
            {"Klapetart","Salah satu oleh-oleh khas Manado yang tidak boleh kamu lewatkan adalah klappertart. Kudapan manis sekaligus gurih ini memang dikenal nikmat, terlebih jika disajikan bersama teh atau kopi. Umumnya, klappertart berbahan dasar kelapa, susu, tepung terigu, mentega, dan telur ayam. Meski pertama kali diperkenalkan oleh Belanda, klappertart masih menjadi hidangan favorit di Indonesia.Selain lezat, adanya kandungan susu yang tinggi dalam makanan ini menjadikannya bermanfaat baik bagi tubuh. Mulai dari mencegah osteoporosis, menyeimbangkan tekanan darah, hingga mencegah timbulnya kerusakan gigi adalah beberapa khasiat yang dihasilkan klappertart.  Klappertart sendiri dijual dalam berbagai ukuran, mulai dari cup sampai loyang berdiameter 20 cm. Harganya dipatok Rp25.000 – Rp200.000 sesuai dengan ukuran kemasan yang dipilih.","https://blog.traveloka.com/source/uploads/2018/08/15802987_1093046487461366_5223195988788772864_n.jpg"}
    };



    public static ArrayList<Kuliner> getListData(){
        ArrayList<Kuliner> list = new ArrayList<>();
        for (String[] aData : data) {
            Kuliner kuliner = new Kuliner();
            kuliner.setNama(aData[0]);
            kuliner.setKeterangan(aData[1]);
            kuliner.setPhoto(aData[2]);
            list.add(kuliner);
        }
        return list;
    }
}
